### ISSUE TITLE
Add Readme.md

### ISSUE THREAD

**Issue by iswCS110cCCSF** [mmuradCCSF/Glacier-Temperature-Unit-Converter#2]
Readme.md describes what the project is about and serve as the homepage. Please add Readme.md.

**Comment by mmuradCCSF** [comment]
README.md has been added!

**Comment by iswCS110cCCSF** [comment]
This is good. Try to add a screenshot of your JFX application to same readme.md. I think we can do it. You can Google it.

**Comment by mmuradCCSF** [comment]
Done and done.
